website/auth.py
# 'auth.py' handles the routes for user authentication

import string

from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from flask_login import login_user, logout_user, current_user

from .models import User
from . import db

from werkzeug.security import generate_password_hash, check_password_hash
from .generate_password import generate_password

auth = Blueprint("auth", __name__)

@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    # Maintain info in session just in case it is deleted on the frontend
    generated_password = session.get('generated_password', "")
    username = session.get('username', "")
    password = session.get('password', "")
    confirmed_password = session.get('confirmed_password', "")

    submit_event = request.form.get('sign-up-submission-type')

    if request.method == 'POST':
        # Check if the user wants their password to be generated randomly, save user info except password
        username = request.form.get('sign-up-username').lower()
        password = request.form.get('sign-up-password')
        confirmed_password = request.form.get('sign-up-confirm-password')

        '''
            Check if user is trying to generate password. If not, create the account if user 
            filled out the entire form and user doesn't already exist and password meets all 
            criteria
        '''
        if "password-generator" in request.form and submit_event != "enter":
            generated_password = generate_password()

        elif not username or not password or not confirmed_password:
            flash("Please fill out the entire form", category="error")

        elif db.session.query(User.id).filter_by(username=username).first():
            flash(f"A user with the username \"{username}\" already exists, please choose another username", category="error")

        elif password != confirmed_password:
            flash("Passwords don't match", category="error")

        elif len(password) <= 8:
            flash("Password must be more than 8 characters long", category="error")

        elif password.upper() == password:
            flash("Password must have at least one lowercase letter in it", category="error")

        elif password.lower() == password:
            flash("Password must have at least one uppercase letter in it", category="error")

        else:
            password_has_number = False
            password_has_symbol = False
            for character in password:
                if character in "1234567890":
                    password_has_number = True
                elif character in string.punctuation:
                    password_has_symbol = True

            if not password_has_symbol:
                flash("Password must have at least one symbol", category="error")

            elif not password_has_number:
                flash("Password must have at least one number", category="error")

            else:
                # Add user to website, log them in, and redirect them to home page
                new_user = User(username=username, password=generate_password_hash(password, method="scrypt"))
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user, remember=True)
                flash(f"Hello {username}!", category="success")

                # Remove user data from session since authentication is complete
                session.pop('generated_password', None)
                session.pop('username', None)
                session.pop('password', None)
                session.pop('confirmed_password', None)

                return redirect(url_for('views.home'))

        if generated_password and "password-generator" in request.form and submit_event != "enter":
            flash(f"Your new generated password is {generated_password}", category="success")

            # When user generates password, user info is deleted on frontend. Save it here to pass to 'render_template'
            session['generated_password'] = generated_password
            session['username'] = username
            session['password'] = password
            session['confirmed_password'] = confirmed_password
            return redirect(url_for('auth.sign_up', user=current_user, generated_password=generated_password, username=username, password=password, confirmed_password=confirmed_password))

    return render_template('sign_up.html', user=current_user, generated_password=generated_password, username=username, password=password, confirmed_password=confirmed_password)

@auth.route("/login", methods=['GET', 'POST'])
def login():
    username = ""

    if request.method == 'POST':
        username = request.form.get('login-username').lower()
        password = request.form.get('login-password')
        user_account = User.query.filter_by(username=username).first()

        # Check if user filled out form and user exists and password is correct. If so, redirect user to home page
        if not username or not password:
            flash("Please fill out the entire form", category="error")

        elif user_account:
            if check_password_hash(pwhash=user_account.password, password=password):
                login_user(user_account, remember=True)

                # Ensure info from sign up form is deleted
                session.pop('generated_password', None)
                session.pop('username', None)
                session.pop('password', None)
                session.pop('confirmed_password', None)

                flash(f"Hello {username}!", category="success")
                return redirect(url_for('views.home'))
            
            else:
                flash("Incorrect password, please try again", category="error")

        else:
            flash(f"There is no account with the username \"{username}\"", category='error')

    return render_template('login.html', user=current_user, username=username)

@auth.route("/logout")
def logout():
    logout_user()
    flash("Logged out successfully", category="success")
    return redirect(url_for('auth.sign_up'))

@auth.route("/terms-of-use", methods=["GET", "POST"])
def terms_of_use():
    return render_template('terms_of_use.html', user=current_user)

@auth.route("/lol", methods=["GET", "POST"])
def lol():
    return render_template('lol.html', user=current_user)

@auth.route("/privacy-policy", methods=["GET", "POST"])
def privacy_policy():
    return render_template('privacy_policy.html', user=current_user)

website/views.py
# 'views.py' handles the routes proceeding user authentication

import os
import random
import json
import math

from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user
from flask_security import login_required

from .models import Goal, Workout, Exercise, GoalAchieved
from . import db

from datetime import datetime, timezone, timedelta
from django.utils.html import escapejs

views = Blueprint('views', __name__)

GOALS_ACHIEVED_UNTIL_AWARD = 3

@views.route("/")
@login_required
def home():
    return render_template('home.html', user=current_user)

@views.route("/manage-goals", methods=['GET', 'POST'])
@login_required
def manage_goals():
    # Handle if the time goes off for the week for duration-based goals
    for goal in Goal.query.filter_by(user=current_user):
        if goal.type == "Duration":
            current_week = math.ceil(((datetime.now(timezone.utc) - goal.date_started.replace(tzinfo=timezone.utc)).days + 1) / 7)

            # If user missed a week, delete the goal
            if current_week - goal.weeks_completed >= 2:
                db.session.delete(goal)
                db.session.commit()
                flash(f"You have missed one or more weeks on \"{goal.title}\", thus failing to meet its requirements. Goal deleted", category="error")
                return redirect(url_for('views.manage_goals'))
            
            # If its next week reset weeks finished status
            elif current_week - goal.weeks_completed == 1:
                goal.is_week_finished = False

    rate = 0
    duration = 0
    if request.method == 'POST':
        utc_now = datetime.now(timezone.utc)

        # Add built in button goal if user clicks one of the buttons on the form
        if "workout-4-weeks" in request.form:
            title, goal_type, description = "Workout for 4 weeks", "Duration", "Workout consistently for 4 weeks 4 times/week"
            rate, duration, weeks_completed = 4, 4, 0
            end_date = utc_now + timedelta(days=28)
            message = "Built in goal created successfully!"
        
        else:
            if "bench-PR" in request.form or "lose-weight" in request.form:
                rate, duration, weeks_completed, end_date = None, None, None, None

                if "bench-PR" in request.form:
                    title, goal_type, description = "Bench PR", "New PR", "Bench your bodyweight ex: if you are 150lbs, you need to bench 150lbs"

                elif "lose-weight" in request.form:
                    title, goal_type, description = "Lose 10% of your weight", "Lose/Gain Weight", "Lose 10% of your bodyweight ex: if you are 100lbs, you need to get to 90lbs"
                
                message = "Built in goal created successfully!"

            else:
                # Add custom goal if user chooses custom goal on the form
                title = request.form.get('goal-title')
                goal_type = request.form.get('goal-type')
                description = request.form.get('goal-description')

                if goal_type == "Duration":
                    rate = int(request.form.get('goal-rate'))
                    duration = int(request.form.get('goal-duration'))
                    weeks_completed = 0
                    end_date = utc_now + timedelta(days=7 * duration)

                else:
                    rate, duration, weeks_completed, end_date = None, None, None, None
                
                message = "Custom goal created successfully!"

        new_goal = Goal(user_id=current_user.id, title=title, type=goal_type, description=description,
                        rate=rate, duration=duration, weeks_completed=weeks_completed, date_started=utc_now,
                        end_date=end_date)
        db.session.add(new_goal)
        db.session.commit()
        flash(message, category="success")
        return redirect(url_for('views.manage_goals'))

    return render_template('manage_goals.html', user=current_user, goals=Goal.query.all())

@views.route('/edit-goal/', methods=['GET', 'POST'])
@login_required
def edit_goal():
    if request.method == 'POST':
        goal_id = int(request.form.get('goal-id'))
        goal = Goal.query.get_or_404(goal_id)
        original_goal_title = goal.title

        goal.title = request.form.get('edit-goal-title')
        goal.description = request.form.get('edit-goal-description')

        db.session.add(goal)
        db.session.commit()

        flash(f"Edited \"{original_goal_title}\" successfully", category="success")
        return redirect(url_for("views.manage_goals"))

    return render_template('manage_goals.html', user=current_user, goals=Goal.query.all())

# Handle what to do when user finishes week on goal of type 'Duration'
@views.route('/<int:goal_id>/handle-finish-week/', methods=['GET', 'POST'])
@login_required
def handle_finish_week(goal_id):
    goal = Goal.query.get_or_404(goal_id)
    weeks_completed = goal.weeks_completed + 1
    current_week = math.ceil(((datetime.now(timezone.utc) - goal.date_started.replace(tzinfo=timezone.utc)).days + 1) / 7)

    # Ensure the user hasn't missed a week first. If they have, delete the goal
    if current_week - goal.weeks_completed >= 2:
        db.session.delete(goal)
        db.session.commit()
        flash(f"You have missed one or more weeks on \"{goal.title}\", thus failing to meet its requirements. Goal deleted", category="error")
        return redirect(url_for('views.manage_goals'))
    
    # If a user finishes all weeks, mark the goal complete
    elif weeks_completed == goal.duration:
        return redirect(url_for('views.mark_goal_complete', goal_id=goal_id))
    
    # Otherwise, this means they've checked off another week (they haven't finished the goal yet)
    else:
        goal.weeks_completed = weeks_completed
        if goal.weeks_completed == current_week:
            goal.is_week_finished = True
        db.session.add(goal)
        db.session.commit()
        flash("Week completed successfully!", category="success")
        return redirect(url_for('views.manage_goals'))

# Mark a goal as completed
@views.route('/<int:goal_id>/mark-goal-complete/', methods=['GET', 'POST'])
@login_required
def mark_goal_complete(goal_id):
    # Add the achievement
    goal = Goal.query.get_or_404(goal_id)
    goal_title = goal.title
    goal_type = goal.type
    new_goal_achieved = GoalAchieved(title=goal.title,
                            type=goal.type,
                            description=goal.description,
                            rate=goal.rate,
                            duration=goal.duration,
                            date_started=goal.date_started,
                            date_finished=datetime.now(timezone.utc),
                            user_id=current_user.id)
    db.session.add(new_goal_achieved)
    db.session.commit()

    # Delete the goal
    db.session.delete(goal)
    db.session.commit()

    # Tell the user if they just achieved a built in award or how far they are from one
    goal_type_achievements_num = len(list(GoalAchieved.query.filter_by(user=current_user, type=goal_type)))
    award_message = ""

    if goal_type_achievements_num == GOALS_ACHIEVED_UNTIL_AWARD:
        flash(f"Congratulations, you have achieved a \"{goal_type}\" award! You can now view this in \"Achievements\"!", category="award")
    
    elif goal_type_achievements_num < GOALS_ACHIEVED_UNTIL_AWARD:
        award_message = f" You are {GOALS_ACHIEVED_UNTIL_AWARD - goal_type_achievements_num} goal(s) achieved of type \"{goal_type}\" away from a built in award for \"{goal_type}\"!"

    flash(f"Completed \"{goal_title}\"!{award_message} You can view this goal achieved now in \"Achievements\".", category="success")
    return redirect(url_for('views.manage_goals'))

# Delete a goal from the database
@views.route('/<int:goal_id>/delete-goal/', methods=['GET', 'POST'])
@login_required
def delete_goal(goal_id):
    goal = Goal.query.get_or_404(goal_id)
    goal_title = goal.title

    db.session.delete(goal)
    db.session.commit()

    flash(f"Deleted \"{goal_title}\" successfully", category="success")
    return redirect(url_for('views.manage_goals'))

with open(os.path.abspath(os.path.dirname(__file__)) + '/workout_quotes.txt', encoding="utf-8") as f:
    lines = f.read().splitlines()

DAYS_ORDER = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

@views.route("/manage-workouts", methods=['GET', 'POST'])
@login_required
def manage_workouts():
    if request.method == 'POST':
        workout_title = request.form.get('workout-title')
        workout_description = request.form.get('workout-description')

        # The immutable dictionary first has all the titles, then all the descriptions in corresponding order of the form. Put titles and
        # descriptions in lists
        added_input_titles = []
        added_input_descriptions = []
        request_form_data = dict(request.form)
        del request_form_data["workout-title"]
        del request_form_data["workout-description"]

        for name, value in request_form_data.items():
            if "title" in name:
                added_input_titles.append(value)
            elif "description" in name:
                added_input_descriptions.append(value)

        new_workout = Workout(title=workout_title, description=workout_description, user_id=current_user.id)
        db.session.add(new_workout)
        db.session.commit()

        # Then, add each title and description to a new exercise
        for i in range(len(added_input_titles)):
            next_exercise_title = added_input_titles[i]
            next_exercise_description = added_input_descriptions[i]
            new_exercise = Exercise(title=next_exercise_title, description=next_exercise_description, workout_id=new_workout.id)
            db.session.add(new_exercise)
            db.session.commit()

website/templates/base.html
<!--'base.html' is the file that all pages on the website are designed around-->

<html>
<head>
    <title>{% block title %}{% endblock %}</title>

    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous"
    >

    <style>
        html
        {
            width: device-width;
            border-style: solid;
            border-color: lightgreen;
            border-width: 0 20px 20px 20px; /* Remove top border */
            box-sizing: border-box;
            min-height: 100vh;
        }
        #preloader
        {
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            z-index: 9999;
            background-color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .spinner
        {
            border: 16px solid #f3f3f3;
            border-top: 16px solid #3498db;
            border-radius: 50%;
            width: 120px;
            height: 120px;
            animation: spin 2s linear infinite;
        }
        @keyframes spin
        {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        .content
        {
            visibility: hidden;
            opacity: 0;
            transition: visibility 0s 1s, opacity 1s ease;
            padding: 0 40px 0px 40px;
            display: grid;
        }
        /* Customize navbar colors */
        nav.navbar-custom
        {
            background-color: lightgreen !important;
        }
        .navbar-custom .navbar-brand,
        .navbar-custom .nav-link
        {
            color: #007bff;
        }
        .navbar-custom .nav-link:hover,
        .navbar-custom .nav-link:focus
        {
            color: #0056b3;
        }
        .award
        {
            background-color: gold;
        }
    </style>

    <!--Bootstrap-->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/auth.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/views.css') }}">

    <!--Styles in each individual HTML file override any others (it is last style specified)-->
    <style>{% block stylesheets %}{% endblock %}</style>
     <!--Styles in each individual HTML file override any others (it is last style specified)-->
</head>
<body>
    <div id="preloader">
      <div class="spinner"></div>
    </div>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-custom">
      <div class="container-fluid">
        <a class="navbar-brand nav-link" href="{{ url_for('views.home') }}">Louis Fitness</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.manage_goals') }}">Manage Goals</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.manage_workouts') }}">Manage Workouts</a>
            </li>
              <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.achievements') }}">Achievements</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
          {% endif %}
        </div>
      </div>
    </nav>
    <!--Navbar-->
    
    <!--Display flashed messages-->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% elif category == 'success' %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% elif category == 'award' %}
            <div class="alert alert-success alert-dismissible fade show award" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}
    <!--Display flashed messages-->
    </br>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <!--Boostrap-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <!--Boostrap-->
    <script src="{{ url_for('static', filename='index.js') }}"></script>
    <script src="{{ url_for('static', filename='manage_goals.js') }}"></script>
    <script src="{{ url_for('static', filename='manage_workouts.js') }}"></script>
    <script src="{{ url_for('static', filename='achievements.js') }}"></script>
    <script src="{{ url_for('static', filename='auth.js') }}"></script>
    <script>
        window.addEventListener('load', function()
        {
            // Hide the preloader
            const preloader = document.getElementById('preloader');
            preloader.style.opacity = '0';
            preloader.style.visibility = 'hidden';

            // Show the main content
            document.querySelector('.content').style.visibility = 'visible';
            document.querySelector('.content').style.opacity = '1';
        });
    </script>
    <script>{% block scripts %}{% endblock %}</script>
</body>
</html>

website/templates/home.html
<!--'home.html' shows the home page of the website-->

{% extends "base.html" %}

{% block title %}Louis Fitness{% endblock %}

{% block stylesheets %}
    .center
    {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    .goggins
    {
        position: relative; /* Enables positioning */
        width: 60vw; 
        height: 60vh;
        object-fit: cover;
    }
{% endblock %}

{% block content %}
    <h1 align="center">Hello {{ user.username }}!</h1>
    </br>
    <h3 align="center">Maintain consistency and set new PR's by keeping track of your workouts</h3>
    <img class="center goggins" src="/static/images/goggins.png" alt="Goggins">
{% endblock %}

website/templates/login.html
<!--'login.html' shows the page the user uses to log into the website-->

{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <h3 align="center">Login</h3>
    </br>
    </br>
    </br>
    <div class="auth-form">
        <form oninput="saveLoginData()" method="post" id="login-form" novalidate>
            <p>Login Here!</p>
            <hr>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <input type="text" class="form-control" name="login-username" id="login-username" placeholder="Username" required="required" value="{{ username }}">
                </div>
            </div>
            </br>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <input type="password" class="form-control" name="login-password" id="login-password" placeholder="Password" required="required">
                </div>
            </div>
            </br>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg">Login</button>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/lol.html
<!--'lol.html' is a funny link the user clicks from terms of service page-->

{% extends 'base.html' %}

{% block title %}lol{% endblock %}

{% block content %}
    <p align="center">Imagine actually clicking this link....</p>
{% endblock %}

website/templates/privacy_policy.html
<!--'privacy_policy.html' shows the user the VERY IMPORTANT privacy policy of the website-->

{% extends 'base.html' %}

{% block title %}Privacy Policy{% endblock %}

{% block content %}
    <h1 align="center">Privacy Policy</h1>
    </br>
    </br>
    </br>
    <p align="center">
        Your privacy is not important to us.
    </p>
{% endblock %}

website/templates/sign_up.html
<!--'sign_up.html' shows the page users use to sign into the website-->

{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block stylesheets %}
	.password-generator
	{
		background-color: lightgreen;
	}
{% endblock %}

{% block content %}
    <h3 align="center">Sign Up</h3>
    </br>
    </br>
    </br>
    <div class="auth-form">
		<form oninput="saveSignUpData()" method="post" id="sign-up-form" novalidate>
			<p>Please fill in this form to create an account!</p>
			<hr>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"></span>
					<input type="text" class="form-control" name="sign-up-username" id="sign-up-username" placeholder="Username" required="required" value="{{ username }}">
				</div>
			</div>
			</br>
			<label>Password criteria: Must be more than 8 characters long, have at least one uppercase and lowercase letter, and at least one symbol</label>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"></span>
					{% if generated_password %}
						<input type="password" class="form-control" name="sign-up-password" id="sign-up-password" placeholder="Password" required="required" value="{{ generated_password }}">
					{% else %}
						<input type="password" class="form-control" name="sign-up-password" id="sign-up-password" placeholder="Password" required="required" value="{{ password }}">
					{% endif %}
				</div>
			</div>
			<div class="form-group">
				<button type="submit" class="password-generator" name="password-generator">Generate Password</button>
			</div>
			</br>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"></span>
					{% if generated_password %}
						<input type="password" class="form-control" name="sign-up-confirm-password" id="sign-up-confirm-password" placeholder="Confirm Password" required="required" value="{{ generated_password }}">
					{% else %}
						<input type="password" class="form-control" name="sign-up-confirm-password" id="sign-up-confirm-password" placeholder="Confirm Password" required="required" value="{{ confirmed_password }}">
					{% endif %}
				</div>
			</div>
			<div>By signing up, you agree to the <a href="{{ url_for('auth.terms_of_use') }}">Terms of Use</a> &amp; <a href="{{ url_for('auth.privacy_policy') }}">Privacy Policy</a></div>
			</br>
			<!-- Hidden field to store submission type -->
			<input type="hidden" id="sign-up-submission-type" name="sign-up-submission-type">
			<!-- Hidden field to store submission type -->
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-lg" name="sign-up-submit-button" value="sign-up-submit-button" onclick="removeSignUpData(); setSignUpSubmissionType('button')">Sign Up</button>
			</div>
		</form>
		<div class="text-center">Already have an account? <a href="{{ url_for('auth.login') }}">Login here</a></div>
	</div>
{% endblock %}

website/templates/terms_of_use.html
<!--'terms_of_use.html' shows the user the terms the user must comply by before signing up-->

{% extends 'base.html' %}

{% block title %}Terms Of Use{% endblock %}

{% block stylesheets %}
    .terms-of-use
    {
        text-align: center;
    }
{% endblock %}

{% block content %}
    <h1 align="center">Terms Of Use</h1>
    </br>
    </br>
    </br>

    <div class="terms-of-use">
        <h4>1. Acceptance of Terms</h4>
        <p>By using [Louis Fitness] ("Website"), you agree to these Terms of Use. If you do not agree, please do not use the Website and kindly scram and never return. Thank you.</p>
        </br>

        <h4>2. Use of Website</h4>
        <p>You agree to use the Website legally and respectfully, respectfully and legally, legally-respectfully, and everything in between.</p>
        </br>

        <h4>3. Intellectual Property</h4>
        <p>Content on the Website is owned by [Louis Fitness] and protected by law. Do not use it without permission, unless you preorder 100 cases of our protein powder (with 100000g of organic-quality-tasty protein per scoop) located <a href="{{ url_for('auth.lol') }}">here</a></p>
        </br>

        <h4>4. Privacy</h4>
        <p>Your use of the Website is also subject to our Privacy Policy, which I will not provide a hyperlink for so you have to suffer and click the back button to the sign up form to click it.</p>
        </br>

        <h4>5. Limitation of Liability</h4>
        <p>We provide the Website "as is" and are not responsible for any damages or losses resulting from your complete and obvious misusing of our website.</p>
        </br>

        <h4>6. Changes to Terms</h4>
        <p>We may update these Terms occasionally and almost all the time, never notify you. Continued use of the Website means you accept the new Terms.</p>
        </br>

        <h4>7. Governing Law</h4>
        <p>These Terms are governed by the laws of..............nobody</p>
        </br>

        <h4>8. Contact</h4>
        <p>If you have questions, don't contact me. I am a very busy man and don't have time for questions. Anyway....enjoy our website :).</p>
        </br>
    </div>
{% endblock %}